title: Settings
data:
  site_name: mark.fullbrook
  social:
    -
      name: Twitter
      url: 'https://twitter.com/m_fullbrook'
      svg_icon: svg/twitter.svg
    -
      name: Github
      url: 'https://github.com/mfullbrook'
      svg_icon: svg/github.svg
    -
      name: Instagram
      url: 'https://www.instagram.com/markfullbrook'
      svg_icon: svg/instagram.svg
  primary: yellow
  body_bg: gray-700
